### PR TITLE
Toggle button for hammer source

### PR DESCRIPTION
**Pull request by iamtekeste**
**DO NOT MERGE!!** 
please clone this branch and give it a test before you merge it. I am confident that it works as expected but you should test by yourself too!!

As of right now this will let you switch between mouse click and camera motion. Even though it stops from the camera detection from running, it does not actually turn off the camera. This technically should not be a problem, but I will see what I can to actually turn of the camera.
@scottpreston  @calebeno

### CODE REVIEW

**Comment by scottpreston** [comment]
Can someone else test/review? I'm working on the new stand for the tarp/screen, don't have the time.

**Comment by calebeno** [comment]
I just added some css updates to the toggle button.  It also defaults to the mouse for the moment.  Once you activate the camera and then turn it off it then on again it no longer works.  Haven't figured that one out just yet.

**Comment by calebeno** [comment]
Fixed the webcam not restarting.  Also I removed the css borders on the buttons because it was causing a weird glitch.

**Review by calebeno — APPROVED** [review]
Looks good!

**Pull request merged**
